services:
    db:
        # Recommended version for new users
        image: postgis/postgis:17-3.5
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                - DEVELOPMENT=${DEVELOPMENT}
        volumes:
            - ./backend:/app
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        command: "python manage.py runserver 0.0.0.0:8000"
        restart: unless-stopped

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - /app.next
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=${NODE_ENV}
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
            - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
        depends_on:
            - backend
        restart: unless-stopped
