# Generated by Django 3.2.25 on 2024-12-07 12:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241207_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
