# Generated by Django 3.2.25 on 2024-12-08 10:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
