# Generated by Django 3.2.25 on 2024-12-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_maintenancetask_rentalapplication_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='cost_per_month',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10, verbose_name='Cost Per Month'),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Has Parking'),
        ),
        migrations.AddField(
            model_name='unit',
            name='listed_on',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Listed On'),
        ),
        migrations.AddField(
            model_name='unit',
            name='number_of_bathrooms',
            field=models.IntegerField(default=1, verbose_name='Number of Bathrooms'),
        ),
        migrations.AddField(
            model_name='unit',
            name='number_of_bedrooms',
            field=models.IntegerField(default=1, verbose_name='Number of Bedrooms'),
        ),
        migrations.AddField(
            model_name='unit',
            name='pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Pet Friendly'),
        ),
        migrations.AddField(
            model_name='unit',
            name='square_footage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Square Footage'),
        ),
    ]
