# Generated by Django 3.2.25 on 2024-12-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20241212_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='listed_on',
            field=models.DateField(auto_now_add=True, verbose_name='Listed On'),
        ),
    ]
