# Generated by Django 3.2.25 on 2024-12-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_unit_listed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='cost_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Per Month'),
        ),
    ]
