# Generated by Django 3.2.25 on 2024-12-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20241217_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='available_from',
            field=models.DateField(null=True, verbose_name='Available From'),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Furnished'),
        ),
        migrations.AddField(
            model_name='unit',
            name='lease_term',
            field=models.IntegerField(default=12, verbose_name='Lease Term (months)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Security Deposit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('townhouse', 'Townhouse')], default='Apartment', max_length=50, verbose_name='Unit Type'),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='utilities_included',
            field=models.BooleanField(default=False, verbose_name='Utilities Included'),
        ),
    ]
